#!/bin/bash
folder=~/Dissertacao/datasets
src_folder=$folder/motox/orto25.11.2014/protasio/
dst_folder=$folder/motox/orto25.11.2014/protasio_selected/


#rm $folder/motox/VID_20140617_162058756_GRAY_equalized_small_ESCOLHA2/* -r
mkdir $dst_folder &>  /dev/null

#for i in `seq 0 15 624`; do #região do corredor
#for i in `seq 624 7 948`; do #região curva do corredor para a grama
#for i in `seq 948 15 2330`; do #região da grama
#for i in `seq 2330 7 2480`; do #região curva da grama para o 2nd corredor
#for i in `seq 2480 15 2980`; do #região 2nd corredor
#for i in `seq 2980 7 3210`; do #região 2nd corredor para 2nd grama
#for i in `seq 3210 15 4435`; do #região 2nd corredor para 2nd grama
#for i in `seq 4435 7 4660`; do #região 2nd grama para 1nd corredor novamente
#for i in `seq 4660 15 5170 `; do #região 1nd corredor novamente
#for i in `seq 5170 7 5375 `; do #região 1nd corredor novamente
#for i in `seq 5375 15 6595 `; do #região 1nd corredor novamente
#for i in `seq 6595 7 6800 `; do #região 1nd corredor novamente
#for i in `seq 6800 15 7840 `; do #região 1nd corredor novamente
#for i in `seq 7840 7 8020 `; do #região 1nd corredor novamente
#for i in `seq 8020 15 9235 `; do #região 1nd corredor novamente
#for i in `seq 9235 7 9465 `; do #região 1nd corredor novamente
#for i in `seq 9465 15 10695 `; do #região 1nd corredor novamente
#for i in `seq 10695 7 10765 `; do #região 1nd corredor novamente
#for i in `seq 10765 15 12100 `; do #região 1nd corredor novamente
#for i in `seq 12100 7 12225 `; do #região 1nd corredor novamente
#for i in `seq 12225 15 12830 `; do #região 1nd corredor novamente
#for i in `seq 12830 7 12900 `; do #região 1nd corredor novamente
#for i in `seq 12900 15 14265 `; do #região 1nd corredor novamente
#for i in `seq 14265 7 14370 `; do #região 1nd corredor novamente
#for i in `seq 14370 15 14990 `; do #região 1nd corredor novamente
#for i in `seq 14990 7 15040 `; do #região 1nd corredor novamente
#for i in `seq 15040 15 16365 `; do #região 1nd corredor novamente
#for i in `seq 16365 7 16430 `; do #região 1nd corredor novamente
#for i in `seq 16430 15 17040 `; do #região 1nd corredor novamente
#for i in `seq 17040 7 17100 `; do #região 1nd corredor novamente
#for i in `seq 17100 15 18435 `; do #região 1nd corredor novamente
#for i in `seq 18435 5 18500 `; do #região 1nd corredor novamente
for i in `seq 0 20 7110 `; do #região 1nd corredor novamente

#for i in `seq 0 7 12580 `; do #região 1nd corredor novamente
    cp $src_folder`printf "I_%06d.png" $i` $dst_folder`printf "I_%06d.png" $i`
done

#rename_images $dst_folder
