#!/usr/bin/python
# -*- coding: utf8 -*-
import matplotlib.pyplot as plt
from matplotlib.pyplot import subplots,cm
from matplotlib.gridspec import GridSpec
import numpy as np, os, sys, csv, utm

def showHelp():
    print """
Plot GPS information from IMU 'Project'

    $ gps_plot gpsFile

          """
    sys.exit()


if len(sys.argv) < 2:
    showHelp()

gpsFile = os.path.expanduser(sys.argv[1])

print "GPS file: ", gpsFile

rows = []

for line in csv.reader(open(gpsFile,"r"),delimiter=";"):
    rows.append([float(col) for col in line])
    rows[-1] += utm.from_latlon(rows[-1][2], rows[-1][3])

systemNanoTime, utcMilliTime, latitude, longitude, altitude, speed, bearing, utmx, utmy, zoneNro, zoneChar = zip(*rows)


plt.plot(utmx, utmy,"g-")
plt.show()

print "\n".join(["new google.maps.LatLng(" + str(latitude[i])+", "+str(longitude[i]) + ")," for i in range(len(latitude))])
