#!/usr/bin/python
# -*- coding: utf8 -*-
import csv, os, sys
from math import sqrt

def showHelp():
    print """

    $ gpsSubset gpsFile1 outputFile [distance]

          """
    sys.exit()

def distance(pt1,pt2):
    return sqrt((pt2[0]-pt1[0])**2 + (pt2[1]-pt1[1])**2)


if len(sys.argv) < 3:
    showHelp()

gpsFile1 = os.path.expanduser(sys.argv[1])
outputFile = os.path.expanduser(sys.argv[2])

minDistance = 0.00009 #Equivale a +- 10 metros
if len(sys.argv)>3:
    minDistance = float(sys.argv[3]) #0.00009 #Equivale a +- 10 metros

print "1º GPS file: ", gpsFile1
print "Distance: ", minDistance
print "Output file: ", outputFile

gpsFile1 = [l for l in csv.reader(open(gpsFile1),delimiter=";")]

correspondence = []
lastPoint = None
for row1 in gpsFile1:

    curPoint = (float(row1[1]),float(row1[2]))

    if lastPoint == None or distance(curPoint, lastPoint) > minDistance:
        correspondence.append(row1)
        lastPoint = curPoint



csv.writer(open(outputFile,"w"),delimiter="-").writerows(correspondence)

