#!/usr/bin/python
# -*- coding: utf8 -*-
import csv, os, sys
from math import sqrt

def showHelp():
    print """

    $ gpsSelectByDistance gpsFile outputFile [distance]

          """
    sys.exit()

def distance(pt1,pt2):
    return sqrt((pt2[0]-pt1[0])**2 + (pt2[1]-pt1[1])**2)


if len(sys.argv) < 3:
    showHelp()

gpsFile = os.path.expanduser(sys.argv[1])
outputFile = os.path.expanduser(sys.argv[2])

minDistance = 0.00009 #Equivale a +- 10 metros
if len(sys.argv)>3:
    minDistance = float(sys.argv[3]) #0.00009 #Equivale a +- 10 metros

print "GPS file: ", gpsFile
print "Distance: ", minDistance
print "Output file: ", outputFile

gpsFile = [l for l in csv.reader(open(gpsFile),delimiter=";")]

correspondence = []
lastPoint = None
for row in gpsFile:

    curPoint = (float(row[1]),float(row[2]))

    if lastPoint == None or distance(curPoint, lastPoint) > minDistance:
        correspondence.append(row)
        lastPoint = list(curPoint)



csv.writer(open(outputFile,"w"),delimiter=";").writerows(correspondence)

