#!/usr/bin/python
# -*- coding: utf8 -*-
import csv, os, sys, md5, time, webbrowser

def showHelp():
    print """

    $ gpsToMaps gpsFile [outputFile]

          """
    sys.exit()


if len(sys.argv) < 2:
    showHelp()

gpsFile = os.path.expanduser(sys.argv[1])

outputFile = "/tmp/"+md5.md5(str(time.time())).hexdigest()+".html"

if len(sys.argv) > 2:
    outputFile = os.path.expanduser(sys.argv[2])


gpsData = [l for l in csv.reader(open(gpsFile),delimiter=";")]

print "GPS file: ", gpsFile
print "Output file: ", outputFile

pts = ""
for row in gpsData:
    pts += "\t\t\t\tnew google.maps.LatLng({0}, {1}),\n".format(row[2],row[3])

output = """
<!DOCTYPE html>
<html>
  <head>
    <style type="text/css">
      html, body, #map-canvas { height: 100%; margin: 0; padding: 0;}
    </style>
    <script type="text/javascript"
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBT7sKs6NJs4a9hwkp1WKP29Mpww0axNKI">
    </script>
    <script type="text/javascript">
      function initialize() {
        var mapOptions = {
          center: { lat: -30.046626, lng: -51.178489},
          zoom: 13
        };
        var map = new google.maps.Map(document.getElementById('map-canvas'),
            mapOptions);
            
          var flightPlanCoordinates = [
"""
output += pts
output += """
          ];
          var flightPath = new google.maps.Polyline({
            path: flightPlanCoordinates,
            geodesic: true,
            strokeColor: '#FF0000',
            strokeOpacity: 1.0,
            strokeWeight: 2
          });

          flightPath.setMap(map);

      }
      
      google.maps.event.addDomListener(window, 'load', initialize);
    </script>
  </head>
  <body>
<div id="map-canvas"></div>
  </body>
</html>
"""

open(outputFile,"w").write(output)
webbrowser.open(outputFile)
