#!/usr/bin/python

import matplotlib.pyplot as plt
from numpy import *
from scipy.misc import *
import sys, os


def showHelp():
    print """
Plot correspondence matrix

    $ showCorrespondenceMatrix imageFile

          """
    sys.exit()


if len(sys.argv) < 2:
    showHelp()

imageFile = os.path.expanduser(sys.argv[1])

img = imread(imageFile)
plt.imshow(img)
plt.colorbar()
plt.xlabel("Test")
plt.ylabel("Query")
plt.show()

