#!/usr/bin/python

import matplotlib.pyplot as plt
from numpy import *
from scipy.misc import *
import sys, os, csv


def showHelp():
    print """
Plot correspondence matrix

    $ showCorrespondenceMatrix imageFile [groundTruth]

          """
    sys.exit()


if len(sys.argv) < 2:
    showHelp()

imageFile = os.path.expanduser(sys.argv[1])

groundTruth = None
if len(sys.argv) == 3:
    groundTruth = os.path.expanduser(sys.argv[2])
plotName = imageFile.split("/")[-1].split(".")[0]
img = imread(imageFile)
ma, mi = 1.0, 0.0
imgMax, imgMin = img.max(), img.min()
img = (ma-mi)*(img - imgMin)/(imgMax - imgMin) + mi
plt.imshow(img)
plt.colorbar()
plt.xlabel("Test Image")
plt.ylabel("Query Image")
plt.title(plotName)

if groundTruth != None:
    lines = [[int(c[0]),int(c[1])]for c in csv.reader(open(groundTruth),delimiter="-")]
    y,x = zip(*lines)
    plt.plot(x,y)
plt.show()

